### ISSUE TITLE
What happened to vim-wrapper?

### ISSUE THREAD

**Issue by klaaspieter** [dmerejkowsky/bwataout#8]
When researching ways to remote control vim I ran across your post about never typing the same path twice: https://dmerej.info/blog/post/never-type-the-same-path-twice/. I was curious about your vim-wrapper script and was surprised it's no longer available in the repo. Looking through the history I see it was intentionally removed and now I'm curious why 😄 

Thank you 🙏

**Comment by dmerejkowsky** [comment]
Well, for starters it's buggy - if you run `sudo vim` you may write `/tmp/nvim-cwd`as root, which means your regular user won't be to update the file. 

I think the main reason I stopped using it is that it felt like too much of a hack. But to be honest I don't remember much else - it was a long time ago :)

**Comment by klaaspieter** [comment]
Do you have an alternative? I really liked some of the ideas in your post.

Either way good to know that it was buggy. I won't try to replicate it 😅

**Comment by dmerejkowsky** [comment]
> Do you have an alternative? 

Well, I'm using kakoune now and a set of Rust programs you can find on this repo. Maybe one day I'll write a blog post on how that works :)

But that being said, you can still start from the code I wrote years ago, it mostly works and the bug may not be hard to fix ;)
